# Generated by Django 4.2.7 on 2025-04-28 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Sobrenome')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de registro')),
                ('role', models.CharField(choices=[('motorista', 'Motorista'), ('logistica', 'Logística'), ('admin', 'Administrador')], max_length=30, verbose_name='Função')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, verbose_name='Número CNH')),
                ('cnh_categoria', models.CharField(blank=True, max_length=5, verbose_name='Categoria CNH')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/perfil/', verbose_name='Foto de Perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
