# Generated by Django 5.2.1 on 2025-06-01 01:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='Hash SHA-256 do token para segurança', max_length=64, unique=True, verbose_name='Hash do Token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(help_text='Token expira em 24 horas', verbose_name='Expira em')),
                ('used_at', models.DateTimeField(blank=True, help_text='Quando o token foi usado para redefinir senha', null=True, verbose_name='Usado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP que solicitou o reset', null=True, verbose_name='IP de Criação')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Número de tentativas de uso do token', verbose_name='Tentativas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de Reset de Senha',
                'verbose_name_plural': 'Tokens de Reset de Senha',
                'ordering': ['-created_at'],
            },
        ),
    ]
