# Generated by Django 5.2.1 on 2025-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Um usuário com este CPF já existe.'}, help_text='CPF com 11 dígitos (apenas números)', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone com DDD', max_length=15, verbose_name='Telefone'),
        ),
    ]
