# Generated by Django 5.2.1 on 2025-06-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Código de Reset de Senha', 'verbose_name_plural': 'Códigos de Reset de Senha'},
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='token_hash',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='code_hash',
            field=models.CharField(default='lixo', help_text='Hash SHA-256 do código de 6 dígitos para segurança', max_length=64, unique=True, verbose_name='Hash do Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='attempts',
            field=models.PositiveIntegerField(default=0, help_text='Número de tentativas de uso do código (máximo 3)', verbose_name='Tentativas'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(help_text='Código expira em 30 minutos', verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Quando o código foi usado para redefinir senha', null=True, verbose_name='Usado em'),
        ),
    ]
