# Generated by Django 5.2.1 on 2025-06-06 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ot', models.CharField(help_text='Número único da Ordem de Transporte (gerado automaticamente)', max_length=20, unique=True, verbose_name='Número da OT')),
                ('status', models.CharField(choices=[('INICIADA', 'Iniciada'), ('EM_CARREGAMENTO', 'Em Carregamento'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('ENTREGUE_PARCIAL', 'Entregue Parcialmente'), ('CANCELADA', 'Cancelada')], default='INICIADA', help_text='Status atual da Ordem de Transporte', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a OT foi criada', verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação', verbose_name='Última Atualização')),
                ('data_finalizacao', models.DateTimeField(blank=True, help_text='Data e hora em que a OT foi finalizada (entregue/cancelada)', null=True, verbose_name='Data de Finalização')),
                ('cliente_nome', models.CharField(help_text='Nome do cliente/empresa destinatária', max_length=200, verbose_name='Nome do Cliente')),
                ('endereco_entrega', models.TextField(help_text='Endereço completo de entrega', verbose_name='Endereço de Entrega')),
                ('cidade_entrega', models.CharField(help_text='Cidade de destino', max_length=100, verbose_name='Cidade de Entrega')),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais sobre a entrega', verbose_name='Observações')),
                ('observacoes_entrega', models.TextField(blank=True, help_text='Observações específicas do momento da entrega', verbose_name='Observações de Entrega')),
                ('latitude_origem', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude do local de criação da OT', max_digits=10, null=True, verbose_name='Latitude de Origem')),
                ('longitude_origem', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude do local de criação da OT', max_digits=11, null=True, verbose_name='Longitude de Origem')),
                ('endereco_origem', models.CharField(blank=True, help_text='Endereço onde a OT foi criada (geocoding reverso)', max_length=255, verbose_name='Endereço de Origem')),
                ('latitude_entrega', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude do local de entrega', max_digits=10, null=True, verbose_name='Latitude de Entrega')),
                ('longitude_entrega', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude do local de entrega', max_digits=11, null=True, verbose_name='Longitude de Entrega')),
                ('endereco_entrega_real', models.CharField(blank=True, help_text='Endereço onde realmente foi entregue (geocoding reverso)', max_length=255, verbose_name='Endereço Real de Entrega')),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a OT está ativa', verbose_name='Ativa')),
                ('motorista_atual', models.ForeignKey(help_text='Motorista responsável atual pela OT', on_delete=django.db.models.deletion.PROTECT, related_name='ots_atuais', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Atual')),
                ('motorista_criador', models.ForeignKey(help_text='Motorista que criou a OT', on_delete=django.db.models.deletion.PROTECT, related_name='ots_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Criador')),
            ],
            options={
                'verbose_name': 'Ordem de Transporte',
                'verbose_name_plural': 'Ordens de Transporte',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atualizacao', models.CharField(choices=[('STATUS', 'Mudança de Status'), ('OBSERVACAO', 'Observação'), ('LOCALIZACAO', 'Atualização de Localização'), ('TRANSFERENCIA', 'Transferência'), ('ARQUIVO', 'Upload de Arquivo'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Atualização')),
                ('descricao', models.TextField(help_text='Descrição da atualização', verbose_name='Descrição')),
                ('observacao', models.TextField(blank=True, help_text='Observação adicional', verbose_name='Observação')),
                ('status_anterior', models.CharField(blank=True, choices=[('INICIADA', 'Iniciada'), ('EM_CARREGAMENTO', 'Em Carregamento'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('ENTREGUE_PARCIAL', 'Entregue Parcialmente'), ('CANCELADA', 'Cancelada')], max_length=20, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(blank=True, choices=[('INICIADA', 'Iniciada'), ('EM_CARREGAMENTO', 'Em Carregamento'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('ENTREGUE_PARCIAL', 'Entregue Parcialmente'), ('CANCELADA', 'Cancelada')], max_length=20, verbose_name='Status Novo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('endereco', models.CharField(blank=True, help_text='Endereço no momento da atualização', max_length=255, verbose_name='Endereço')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atualizacoes_ot', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('ordem_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='core.ordemtransporte', verbose_name='Ordem de Transporte')),
            ],
            options={
                'verbose_name': 'Atualização de OT',
                'verbose_name_plural': 'Atualizações de OT',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo anexado à OT', upload_to='ots/arquivos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('CANHOTO', 'Canhoto Assinado'), ('FOTO_ENTREGA', 'Foto da Entrega'), ('FOTO_OCORRENCIA', 'Foto de Ocorrência'), ('COMPROVANTE', 'Comprovante'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo de Arquivo')),
                ('descricao', models.CharField(blank=True, help_text='Descrição do arquivo', max_length=255, verbose_name='Descrição')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('ordem_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.ordemtransporte', verbose_name='Ordem de Transporte')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_ACEITACAO', 'Aguardando Aceitação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=25, verbose_name='Status')),
                ('motivo', models.TextField(help_text='Motivo ou justificativa para a transferência', verbose_name='Motivo da Transferência')),
                ('observacao_aprovacao', models.TextField(blank=True, help_text='Observação do aprovador/rejeitador', verbose_name='Observação da Aprovação/Rejeição')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço da Transferência')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('motorista_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Motorista de Destino')),
                ('motorista_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Motorista de Origem')),
                ('ordem_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.ordemtransporte', verbose_name='Ordem de Transporte')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Transferência de OT',
                'verbose_name_plural': 'Transferências de OT',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemtransporte',
            index=models.Index(fields=['numero_ot'], name='core_ordemt_numero__037a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemtransporte',
            index=models.Index(fields=['status'], name='core_ordemt_status_c378b8_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemtransporte',
            index=models.Index(fields=['motorista_atual'], name='core_ordemt_motoris_8b5365_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemtransporte',
            index=models.Index(fields=['-data_criacao'], name='core_ordemt_data_cr_48d481_idx'),
        ),
    ]
