# Generated by Django 5.2.1 on 2025-06-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciaot',
            name='observacao_aprovacao',
            field=models.TextField(blank=True, help_text='Observação do aprovador/rejeitador', verbose_name='Observação da Aprovação/Rejeição'),
        ),
        migrations.AlterField(
            model_name='transferenciaot',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_ACEITACAO', 'Aguardando Aceitação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=25, verbose_name='Status'),
        ),
    ]
